#baseURL = 'https://example.org/'
#languageCode = 'en-us'
baseURL = "livro/"
title = 'Introdução à Programação e aos Algoritmos'
theme = "hugo-book"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true